### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by hodasemi** [nickbrowne/ears#3]
I need the duration of `Sound`. I see two simple ways:
* expose `sound_data::get_sndinfo`
* build a function that just returns duration (e.g. `Sound::get_duration`)

**Comment by nickbrowne** [comment]
That shouldn't be a problem, I think adding a function to `AudioController` so that both `Sound` and `Music` implement `get_duration` sounds good.

Would returning a https://doc.rust-lang.org/std/time/struct.Duration.html from that function work for you?

**Comment by hodasemi** [comment]
That would work perfectly :)

**Comment by nickbrowne** [comment]
Great, I'll see if I can add that tonight. Otherwise should be some time this weekend.

**Comment by nickbrowne** [comment]
I've just published a new version (0.7.0) that lets you call `get_duration` on both `Sound` and `Music`.

**Comment by hodasemi** [comment]
It works perfectly. Thank you.

**Comment by nickbrowne** [comment]
Good to hear :)
