### ISSUE TITLE
Supported audio file format?

### ISSUE THREAD

**Issue by Losses** [nickbrowne/ears#4]
Hi, thanks for maintaining the great project, is there any list of supported file format? I didn't find anything about this from the document :)

**Comment by nickbrowne** [comment]
That's true, it really should be in the readme :)

Basically it supports any file format that libsndfile does, which is quite a lot, although much of them aren't that widely used these days.

http://www.mega-nerd.com/libsndfile/

I'll list the major ones in the readme shortly.

**Comment by Losses** [comment]
Wow! That's cool! I'd like to write something with `ears`!

**Comment by nickbrowne** [comment]
I've just updated the readme with the following text:

> Supports a wide variety of audio formats, including:
> 
>  * Ogg Vorbis
>  * Microsoft WAV
>  * RAW PCM
>  * Lossless FLAC
>  * AIFF
> 
> For a full list please see the documentation for libsndfile here: http://www.mega-nerd.com/libsndfile/

Hopefully that's a bit more useful!

**Comment by Losses** [comment]
That's cool!
